# Generated by Django 6.1.2 on 2026-10-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(help_text='Name of HR / Hiring Manager', max_length=150)),
                ('company_name', models.CharField(help_text='Registered or trading company name', max_length=200)),
                ('email', models.EmailField(help_text='Official business email address', max_length=254)),
                ('phone', models.CharField(help_text='Direct business phone or mobile number', max_length=20)),
                ('hiring_requirements', models.TextField(help_text='Specify job roles, departments, or positions needed')),
                ('vacancies_count', models.PositiveIntegerField(default=1, help_text='Estimated number of openings to fulfill')),
                ('required_skills', models.TextField(blank=True, help_text='Key technical, commercial, or operational skill requirements')),
                ('message', models.TextField(blank=True, help_text='Additional instructions, budget parameters, or timeline')),
                ('status', models.CharField(choices=[('New', 'New Enquiry'), ('Contacted', 'Contacted / Follow-up'), ('In Discussion', 'In Discussion / Requirement Analysis'), ('Agreement Signed', 'Service Agreement Signed'), ('Closed', 'Fulfilled / Closed')], default='New', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employer Enquiry',
                'verbose_name_plural': 'Employer Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
