# Generated by Django 6.1.2 on 2026-10-09 10:17

import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume_file', models.FileField(help_text='Uploaded resume in PDF or DOCX format (Max 5MB)', upload_to='resumes/applications/%Y/%m/', validators=[accounts.validators.validate_resume_file])),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter or additional notes for the recruiter')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['candidate', '-submitted_at'], name='application_candida_e97e8e_idx'), models.Index(fields=['job', 'status'], name='application_job_id_f7a30b_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_application')],
            },
        ),
    ]
