# Generated by Django 6.1.2 on 2026-10-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this domain or industry')),
                ('icon', models.CharField(default='bi-briefcase', help_text="Bootstrap Icon class name, e.g., 'bi-laptop', 'bi-gear', 'bi-hospital'", max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('employer_name', models.CharField(blank=True, default='Confidential Client', help_text="Client/Employer name or 'Confidential Client' if undisclosed", max_length=200)),
                ('location', models.CharField(help_text='e.g. Mohali, Chandigarh, Delhi NCR, Remote', max_length=150)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='Full-time', max_length=50)),
                ('experience_requirements', models.CharField(choices=[('Fresher', 'Fresher (0 - 1 Years)'), ('1-3 Years', '1 - 3 Years'), ('3-5 Years', '3 - 5 Years'), ('5-8 Years', '5 - 8 Years'), ('8+ Years', '8+ Years'), ('Any Experience', 'Any Experience')], default='Any Experience', max_length=100)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum annual CTC or monthly salary in INR', max_digits=12, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum annual CTC or monthly salary in INR', max_digits=12, null=True)),
                ('salary_negotiable', models.BooleanField(default=False, help_text='Check if salary is negotiable')),
                ('hide_salary', models.BooleanField(default=False, help_text="Check to display 'Best in Industry / Disclosed on Interview'")),
                ('description', models.TextField(help_text='Detailed overview of the job role and position')),
                ('responsibilities', models.TextField(help_text='Bullet points or detailed breakdown of key duties')),
                ('required_skills', models.TextField(help_text='Key skills, tools, and competencies expected')),
                ('qualifications', models.TextField(help_text='Education, certifications, or minimum criteria required')),
                ('application_deadline', models.DateField(blank=True, help_text='Optional last date to receive applications', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this vacancy prominently on the homepage')),
                ('is_published', models.BooleanField(default=True, help_text='Set to False to hold/unpublish this vacancy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.category')),
            ],
            options={
                'verbose_name': 'Job Vacancy',
                'verbose_name_plural': 'Job Vacancies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='jobs_job_is_publ_a9b51b_idx'), models.Index(fields=['slug'], name='jobs_job_slug_9562d1_idx'), models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'), models.Index(fields=['employment_type'], name='jobs_job_employm_743f88_idx')],
            },
        ),
    ]
