# Generated by Django 6.1.2 on 2026-10-09 10:17

import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Contact telephone number', max_length=20)),
                ('location', models.CharField(blank=True, help_text='City, State, or Preferred Location', max_length=150)),
                ('skills', models.TextField(blank=True, help_text='Key skills (e.g. Python, SQL, Project Management, Sales)')),
                ('education', models.TextField(blank=True, help_text='Educational background, highest degree, institution')),
                ('experience_summary', models.TextField(blank=True, help_text='Summary of total work experience, key roles, and domains')),
                ('resume', models.FileField(blank=True, help_text='Upload your resume in PDF or DOCX format (Max 5MB)', null=True, upload_to='resumes/candidate_profiles/', validators=[accounts.validators.validate_resume_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Profile',
                'verbose_name_plural': 'Candidate Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
